### ISSUE TITLE
Set an upper threshold for q scores based on the read length

### ISSUE THREAD

**Issue by gringer** [nanoporetech/dorado#113]
I've been seeing q scores of 90 in nanopore reads, but q scores that suggest accuracies greater than half an error across the entire the length of the read can't be properly validated. I recommend that a fixed upper limit on single-base q scores is used when generating final outputs, assuming this rate (or some other similar length-based statistic).

More formally, assuming `l` is the read length:

$q_{max} = -10 \times log_{10}\frac{0.5}{l}$

A few examples:

* sequence length 1 [I have seen some of these]; $q_{max} = 3$
* sequence length 150 [i.e. Illumina-like]; $q_{max} = 25$
* sequence length 70,000 [?longest perfect duplex]; $q_{max} = 51$
* sequence length 3,200,000 [?longest read]; $q_{max} = 68$

**Comment by iiSeymour** [comment]
We have just been discussing this actually @gringer so good timing. The Q90 bases are down to a FP16 numerical precision issue where we split over 1.0 and clip Qinf to 90. We are looking at fixes currently and should have something to report soon.

**Comment by tdelcourt** [comment]
How should these 90 Q scores be interpreted then? Simply scores which were higher than, say, 40-ish? 
We have data where these bases occur in regions of otherwise lower quality (~40) without any intermediate scores and I wondered if it was something that could influence low-frequency variant calling down the line where such a high Q score of 90 would bias the calling. The reads are usually a couple of hundreds of bases long at most, if that's of any use.

**Comment by ftostevin-ont** [comment]
Our observation is that nearly all of the Q90 bases, when recalculated with higher precision, come out >=40 with a mode around Q43-45. So considering these as bases with scores >=40 is a reasonable approximation.

**Comment by gringer** [comment]
Does this mean that you're not log-transforming p-values before multiplying lots of them together?

**Comment by iiSeymour** [comment]
Resolved in https://github.com/nanoporetech/dorado/releases/tag/v0.2.2

**Comment by gringer** [comment]
Not quite sure why this has been closed. Q scores are still not thresholded based on the read length. Here are the first few reads from a duplex call I just did on a P2 Solo run:

```
$ ~/install/dorado/dorado-0.2.4-linux-x64/bin/dorado basecaller ~/install/dorado/dna_r10.4.1_e8.2_400bps_sup@v4.1.0 pod5/ --emit-moves  | samtools view -b > unmapped_reads_with_moves.bam
...
$ duplex_tools pair --output_dir pairs_from_bam unmapped_reads_with_moves.bam
...
$ ~/install/dorado/dorado-0.2.4-linux-x64/bin/dorado duplex ~/install/dorado/dna_r10.4.1_e8.2_400bps_sup@v4.1.0 pod5/ --pairs pairs_from_bam/pair_ids_filtered.txt | samtools view -b > duplex_orig.bam
...
$ samtools fastq duplex_orig.bam | head -n 40
@6ed45ee7-56fd-4863-85bc-430f369b51c9;4ac25aee-43b2-4f69-9672-e1f2cadf5389
C
+
;
@a5b6b12d-8fdc-4c37-a856-a73c9cc8f884;fae30894-aaa3-456a-ad31-7ea7b88d4128
G
+
%
@2c8eb2df-6440-4e10-ad4a-087c2ec17a79;9a9a0d1a-133e-419d-afee-cc2eec14cf1d
C
+
3
@11ade92d-d7c7-4851-b14c-52fa560bd62e;4c45c2ba-df8b-4654-a64d-797200f557e3
C
+
"
@55c7d6e2-5fd0-488c-9812-ff507942d0cc;00a0e70e-734e-4848-868c-ca02068446b2
T
+
&
@3c79cf66-8655-45cf-9115-d83f0d800c46;94da0597-80d6-4ebb-a2d9-a79d60682e18
G
+
-
@78edb26f-004b-419a-9ce4-e6d477153233;d7c52121-39ce-4884-b421-11b25f2da4ee
G
+
7
@7dbb5eba-7eaf-481b-8b2f-606a2cef06bf;433fc21a-dda6-4df8-94f2-5f52a8543611
GA
+
6G
@1eba0b79-1b9b-4b5f-a837-eb06917080d1;72e63f79-7df8-4d5c-9616-7f7f10f7e1bd
T
+
5
@4b2e1d20-f050-405a-bc7f-3f6d7cf2a41f;134866c0-cd76-4da1-b717-ab2caf260b9c
C
+
B
```

That last one is a claimed q33 accuracy for a single base read. There's *no possible way* to validate accuracy that high for a single base. It wouldn't surprise me to discover that this "read" is actually just sensor noise.

**Comment by gringer** [comment]
On the other end of the scale, here's another read; the longest in the quick duplex run I did:

```
@6a3079c4-f012-4f61-a60d-86e97d3381e5;966130c0-1693-47e7-82bc-4e909150cbbf
TATTGCTCGCCGGGCAAGAGCAACTCGGTCGCCGCATACACTATTCTCAGAATGACTTGGTTGAGTACTCACCAGTCACAGAAAAGCATCTTACGGATGGCATGACAGTAAGAGAATTATGCAGTGCTGCCATAACCATGAGTGATAACACTGCGGCCAACTTACTTCTGACAACGATCGGAGGACCGAAGGAGCTAACCGCTTTTTTGCACAACATGGGGGATCATGTAACTCGCCTTGATCGTTGGGAACCGGAGCTGAATGAAGCCATACCAAACGACGAGCGTGACACCACGATGCCTGTAGCAATGGCAACAACGTTGCGCAAACTATTAACTGGCGAACTACTTACTCTAGCTTCCCGGCAACAATTAATAGACTGGATGGAGGCGGATAAAGTTGCAGGACCACTTCTGCGCTCGGCCCTTCCGGCTGGCTGGTTTATTGCTGATAAATCTGGAGCCGGTGAGCGTGGGTCTCGCGGTATCATTGCAGCACTGGGGCCAGATGGTAAGCCCTCCCGTATCGTAGTTATCTACACGACGGGGAGTCAGGCAACTATGGATGAACGAAATAGACAGATCGCTGAGATAGGTGCCTCACTGATTAAGCATTGGTAACTGTCAGACCAAGTTTACTCATATATACTTTAGATTGATTTAAAACTTCATTTTTAATTTAAAAGGATCTAGGTGAAGATCCTTTTTGATAATCTCATGACCAAAATCCCTTAACGTGAGTTTTCGTTCCACTGAGCGTCAGACCCCGTAGAAAAGATCAAAGGATCTTCTTGAGATCCTTTTTTTCTGCGCGTAATCTGCTGCTTGCAAACAAAAAAACCACCGCTACCAGCGGTGGTTTGTTTGCCGGATCAAGAGCTACCAACTCTTTTTCCGAAGGTAACTGGCTTCAGCAGAGCGCAGATACCAAATACTGTTCTTCTAGTGTAGCCGTAGTTAGGCCACCACTTCAAGAACTCTGTAGCACCGCCTACATACCTCGCTCTGCTAATCCTGTTACCAGTGGCTGCTGCCAGTGGCGATAAGTCGTGTCTTGACCGGGTTGGACTCAAGACGATAGTTACCGGATAAGGCGCAGCGGTCGGGCTGAACGGGGGGTTCGTGCACACAGCCCAGCTTGGAGCGAACGACCTACACCGAACTGAGATACCTACAGCGTGAGCTATGAGAAAGCGCCACGCTTCCCGAAGGGAGAAAGGCGGACAGGTATCCGGTAAGCGGCAGGGTCGGAACAGGAGAGCGCACGAGGGAGCTTCCAGGGGGAAACGCCTGGTATCTTTATAGTCCTGTCGGGTTTCGCCACCTCTGACTTGAGCGTCGATTTTTGTGATGCTCGTCAGGGGGGCGGAGCCTATGGAAAAACGCCAGCAACGCGGCCTTTTTACGGTTCCTGGCCTTTTGCTGGCCTTTTGCTCACATGTTCTTTCCTGCGTTATCCCTGATTCTGTGGATAACCGTATTACCGCCTTTGAGTGAGCTG
+
$?B>>?EEEFMSELLB;?<;..:66477?EIDSEIJHSGLDCPHOCGOSSJPHSLIMSBGSEDGGHEGD555CSDKSKSAFSGSSGGPJKHSIHGSFMESSGSGGIEGSFKGKDSKSSRCCSSSSEIGISIIDSSSESGGGFSRFGDEFGGKQGLIGJIJHHECASGFDJFELSSIDIFFSGFJSKSGEKSSSSNDGJSSMIEDSSSSMGFIHESSFGISSSSSSEKSGGHPIISEEMSGIFSGGSSGSSESFIDFSSSSESGLSSSDSIHHGHHSSESKCFSEHLSDNJDJSHIGNSHMLFSSHJOSSSGELNGEIHFHISHLSSKGSHFEIRISISSIFSSSHSHSGHB@>@?;BGGFSSFQJSMSGHSSH333A;=:7@==CCISMJGKJSHDFEMFGDHSHJSDSIDKFQ?ADGSKDELSNSPSSSHGSGFHGSSDGSSGSSGGSFGSGJSHHSDSHSSESDCHSSFESJGSIGSSSFISHHSESSSFSNGSCSFSMSSMMMEHDISGCSSEESGAPSDEJKDGBGEIJEBKSSGGJCAFSGSSIIMBMJSSSEGNSHBSHGGFSSGFHSGJHEBSLGFGSECJFGDSKCSSESEMSEEDSINSFSIJJSISILFGSSKFHJMSSSESSKKSGKFHHKDOEGDEFGSEDISSHFGDSNISSLDSSDIESSGGHFGFDSSSFGJKG@&%,-CDSSDFDRMFSSSSFGDHHIFGPSHMGNHSSSHESSSSSKSPCGGGDGSSSIFSSILSHJHCSESGICHSPJSFIDGQESSKSDJGGSGGJHSKESISHHDEDSESSDSSSSS@@EGDGGSQISFFDMEJSSISEHSMIESSSSSNSFMGSNHISIMSSIEDSGKMQFCGSEEDA:916,-<DHHCEDDG=@BRSHSSSEFFGKSHSIISSGSGSSMJJHSESSIEHEHSCJHQISSDSHSJHHSLIRGGSSSSGMHGCDFJHSHKSFSIDEGHFGHMHSESHKSFHKOSSSKIILGHSGGSGHFGGJFCGGDSLGIIIFSDLFSHSCFHMHHIHFKFACCCFJSSSEOG6:G>:7=573++#%6?BSGSSLSEEFJOSSHGSSHJSSGEJSHLFSIMEIGSSSGSHICHSSNGGGSHSGSSSSJSESSFHHSKISGSJGGSSHJSIESSGSCSHLLIHFESGFJSFGMSLSJDJSSFFSSSGSSSMJGFJGCISSSSSESEGIPFGJSDBLB=FECSIHSKSESSESNIKGDFGGMSJDNSJKKSFSEFSSNIEFSHIJSSHMDIIIGSHB?BSSESJDFLLSBPEDEFGSLGLDN<<<DSSDSGSHIDJGFDNSHSGSFGGHGSGSHSSDISFGIOIKEMSSFFISSSSSSSSJJSHSSEMSGGGSSSSMGISSSISGDFEGGHSSHHFSFSKGISHSIJHHSMSSHGDGPKDSLCSFSESGSISEDBGSGMISLOEJLIJCGFNNSGSHHB?AJH@888?SDGABIGGSSGGKFJSHSSKEKFSDSKSHHSJSKDFLDEDC@4
```

I'm seeing lots of 'S' in this (29.47% of bases), which corresponds to a q50 accuracy... which could only be validated on a sequence that is longer than 100,000 bases (this sequence is 1500 bases).

**Comment by cjw85** [comment]
@gringer,

I don't believe there's any reason that the quality scores should be a function of the read length. The scores are a prediction of the probability that a basecall of a single base is erroneous. That is not something that is obviously a function of the read length.

Whether the distribution of predicted probabilities well captures the empirical error probabilities (across all reads) is a separate concern.

**Comment by gringer** [comment]
A call of a single base with a reported accuracy of q33 is absurd.

I'm not saying the quality scores should be a function of the read length; I'm saying that the *maximum possible* probabilities should be a function of the read length.

Probabilities with the new duplex caller appear to be capped at S (i.e. q50) for some arbitrary reason. Why not have a more valid reason for capping?

**Comment by vellamike** [comment]
Hi @gringer,

Could you explain why a reported accuracy of Q33 would be absurd? It is true that this would not be verifiable with one short read, but since we don't only validate on one read it is reasonable to have Q scores which exceed the maximum which would be verifiable with the one read that a particular base came from.

**Comment by gringer** [comment]
The accuracy in itself is not absurd, it's that it is attached to a sequence that is one base in length.

A one-base sequence could map perfectly to about a quarter of the bases in a reference genome, even if it had an error, so it doesn't make sense to speculate about where that particular base came from.

When I'm mapping and doing my comparisons of mean Q score with aligned read gap-compressed identity, I compare single reads to single alignments. The only way I have to validate the reported Q scores is by comparing the means against mappings, so if I have a sequence that's 16kb in length, I'm never going to see error rates that are non-zero and less than 1 base in 16,000. Regardless of what the computational model is saying, my own empirical validation will never produce Q values of higher than q42:

![basecalling_consistency](https://user-images.githubusercontent.com/856314/234468696-752b1712-9798-4af3-90b5-2193a442e44a.jpg)

Similarly, in a theoretical world where I *could* map a single-base sequence to its perfect origin, I'm never going to see error rates that are non-zero and less than 1 base in 1.

My reasoning for suggesting half an error across the entire length of the read is that such an accuracy (if present at the same level for all bases) would be indistinguishable from no error. On an individual read level, there's no benefit to be gained from reporting a higher accuracy than that, and there are space-saving benefits from capping at a low accuracy.

**Comment by cjw85** [comment]
I can agree that basecalls of one base are pretty silly, and to any practical extent are useless; they likely result from noise. I agree also that it doesn't make sense to speculate about where a single base should be placed in a reference. However this is unrelated to what single base quality scores are an attempt to convey; they measure the confidence of the basecaller when it's making statements about which bases were present in the system under measurement.

They do not (and should not) make any statement about the correctness of a base conditioned on the known corpus of reference sequences.

> The only way I have to validate the reported Q scores is by comparing the means against mappings, 

This is not the only way to evaluate the veracity of per base quality scores. As stated they convey the certainty in the basecaller that a particular base was present, the error in that belief. When discretized as they are in fastq and bam we can perform regression across the buckets of bases with a given score against truth labels derived from alignments of reads. (If we want we can include notions of mapping ambiguity, MAPQ in BAM speak, in this regression). This sort of regression is used in the production of the quality scores from the basecaller --- the neural network emits an initial estimate of error, which we then "manually" correct with the results of regression analysis.

This regression attempts to ensure that when we label bases with Q20, the empirical error in all bases with that label is 1 in 100.

As an example, consider a read of 100 bases. The proposed method would perhaps have us say that no per base q score should be more than Q20. I would ask why. Why should this be? The basecaller can be more confident in some bases than it is in others. Indeed it can be utterly befuddled about the basecall in some regions but extremely confident in others. It is valid for the basecaller to be emitting a distribution of quality scores.

None of this is to say that capping the scores isn't entirely unwarranted. If we know that the basecaller is irrationally confident in some calls then such a scheme could be implemented. There's certainly scope to improve the quality scores such that the above mentioned correlation is better (I've illustrated this is previous blog posts), but the suggestion of capping per base scores as a function of read length is not valid. The implication is that the veracity of basecalling is affected by read length, which is not trivially the case.

**Comment by gringer** [comment]
> The proposed method would perhaps have us say that no per base q score should be more than ***Q23***. I would ask why. Why should this be? The basecaller can be more confident in some bases than it is in others. Indeed it can be utterly befuddled about the basecall in some regions but extremely confident in others.

It shouldn't be more than Q23 because it's unnecessary and unfalsifiable. That is the same if it's Q24, or Q50, or Q90, and there's no way to distinguish between those three quality scores.
