### ISSUE TITLE
dorado v0.9.0 does not remove adapter sequences from Ultra-long data

### ISSUE THREAD

**Issue by is01** [nanoporetech/dorado#1219]
Hello,
I basecalled ultra-long data with dorado v0.9.0, it seems that ~90 bases of adapter are left.
The adapter trimming worked in v0.8.2.
Is there an additional option required to trim the adapter sequence of the ultra long kit?

## Run environment:
- Dorado version: v0.9.0
- Model: dna_r10.4.1_e8.2_400bps_sup@v5.0.0
- Dorado command: `dorado basecaller -r --reference $fasta --modified-bases 5mC_5hmC $model $pod5 > out.bam`

**Comment by malton-ont** [comment]
Hi @is01,

Thanks for reporting this. dorado 0.9.0 is supposed to select the appropriate adapters and primers to trim based on the sequencing kit detected from the pod5 file. It looks like the ULK kits were missed in the look-up - we'll get a fix out for this asap.

**Comment by malton-ont** [comment]
Hi @is01,

This issue should be resolved in dorado 0.9.1. If it persists, please re-open this ticket.

**Comment by is01** [comment]
@malton-ont  Thank you for your quick response. I will try new version.
thanks.

**Comment by is01** [comment]
I basecalled the ultra-long data with dorado 0.9.1, but the reads still have adapters/primers.
It seems that the RAD primers (transposase sequence) were not removed.
Thanks for help.

**Comment by malton-ont** [comment]
@is01,

Are you able to share a few example reads?

**Comment by is01** [comment]
@malton-ont, 
I'm sorry I can't share the pod5 file, but I found that adapter trimming works fine by specifying a custom primer file.
I ran the following command (dorado 0.9.1):
`dorado basecaller -r --reference $fasta --modified-bases 5mC_5hmC $model $pod5 --primer-sequences primer.fa > out.bam`

Custom primer file: 
```
>RAD_front type=primer kits=SQK-ULK114
GCTTGGGTGTTTAACCGTTTTCGCATTTATCGTGAAACGCTTTCGCGTTTTTCGTGCGCCGCTTCA
```
Is it possible that the above sequence is not searched for in the ULK kit?

**Comment by malton-ont** [comment]
@is01,

Apologies! dorado 0.9.1 added this kit to the adapter search, but is still missing it for the primers. We'll address that in the next release. In the mean time, using the custom primer trimming as you have is the appropriate solution.

**Comment by is01** [comment]
@malton-ont,

Thanks for providing the solution. I look forward to the next release.

**Comment by is01** [comment]
@cblazier,

Thank you for the information, it's very informative.
I thought that there were relatively few internal adapters for ultra-long data and the default Read-splitting would be sufficient, but I'll have to check the remaining adapters.

**Comment by cblazier** [comment]
For us, the number of reads with internal adapters is pretty low, less than 1%, but they tend to be (artificially) long and could mess up a de novo assembly. The bigger concern is probably the number of normal rapid adapters that Dorado leaves on the data, depending on which assembler you're using.

**Comment by malton-ont** [comment]
@is01,

ULK primer trimming has been added to dorado 0.9.5, just released.
