### ISSUE TITLE
dorado downloads fail with 'elz::zip_exception'

### ISSUE THREAD

**Issue by rstorch01** [nanoporetech/dorado#309]
Hello, I have just installed dorado 0.3.2+d8660a3 and I am not able to download models:

dorado download --model dna_r10.4.1_e8.2_260bps_fast@v4.1.0
[2023-07-25 15:00:05.851] [info]  - downloading dna_r10.4.1_e8.2_260bps_fast@v4.1.0
terminate called after throwing an instance of 'elz::zip_exception'
  what():  exception occured when opening archive './dna_r10.4.1_e8.2_260bps_fast@v4.1.0.zip'
Aborted (core dumped)

I tried downloading it to another directory that I made and it downloads a zip file but you can't unzip it:

unzip dna_r10.4.1_e8.2_260bps_fast@v4.1.0.zip
Archive:  dna_r10.4.1_e8.2_260bps_fast@v4.1.0.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.

**Comment by iiSeymour** [comment]
@rstorch01 are you inside a network that requires a HTTP proxy?

**Comment by rstorch01** [comment]
Yes we do have a proxy but I have already turned on proxy access before running this command.  We have many applications running successfully this way.

**Comment by gangwug** [comment]
@iiSeymour Thanks for the quick reply! I saw a closed issue (https://github.com/nanoporetech/dorado/issues/112) in Feb with a similar error ("_terminate called after throwing an instance of 'elz::zip_exception'_"). Is that issue fixed by reproducing? In addition, is there any link that users can directly download the trained models when 'dorado download' does not work well?

**Comment by rstorch01** [comment]
I'm not seeing what the solution was for this post. I am still getting the exact same error. 

I think the whole point of installing dorado for our HPC was the ability to download files.  Is there a way to get it to work as it should?

**Comment by iiSeymour** [comment]
@rstorch01 model downloading is improved in v0.4.0 - can you try that?

**Comment by vellamike** [comment]
Model downloading has changed significantly since Dorado 0.3.2. Closing this issue due to inactivity.
